SOURCES = 42_main.c 42_oop.c
HEADER = 42_oop.h
FLAGS = -g3 -Wall
OUTPUT = application

all:
				@gcc $(FLAGS) $(SOURCES) $(HEADER) -o $(OUTPUT)
				$(info App "$(OUTPUT)" built.)

clean:
				@rm $(OUTPUT)
				$(info App "$(OUTPUT)" removed.)