#Process for C compiler, like gcc
compile_C:		listening5.c
				gcc -g -Wall -o progC.run listening5.c

#Process for C++ compiler, like g++
compile_Cpp:	listening5.c
				g++ -g -Wall -o progCpp.run listening5.c

clean:
				rm progC.run

