ARGUMENTS=-g3 -Wall
SOURCE=24_csv.c 24_main.c 24_csv.h
TARGET=application

C:
							@gcc $(ARGUMENTS) $(SOURCE) -o $(TARGET)
							$(info application (for C) has been created...)

clean:
							@rm $(TARGET)
							$(info application removed...)