#compiling a C/C++ source code with -g → the program has a bigger size of bytes
#and contains useful informations for debugging, like gdb (GNU Debugging)

#divide a number with 0 → floating point exception occurs
crash_01:
					gcc -g -Wall -o 01_crashProgram.run 01_crashProgram.c

#try to convert a datatype into it's pointer type without cast (&) → segmentation fault occurrs
crash_02:
					gcc -g -Wall -o 02_crashProgram.run 02_crashProgram.c

clean:
					rm *.run
